// "use client"

// import { createContext, useContext, useState, type ReactNode } from "react"
// // import { useToast } from "@/hooks/use-toast"

// interface AIModel {
//   id: string
//   name: string
//   description: string
//   type: "text" | "image" | "audio" | "video" | "code"
//   price: string
//   creator: string
//   image: string
//   rating: number
//   downloads: number
//   category: string
//   isRental: boolean
//   rentalPrice?: string
// }

// interface NFTItem {
//   id: string
//   name: string
//   description: string
//   price: string
//   creator: string
//   image: string
//   type: "model" | "prompt" | "output"
//   category: string
//   likes: number
//   views: number
//   isListed: boolean
// }

// interface Proposal {
//   id: string
//   title: string
//   description: string
//   status: "active" | "passed" | "failed" | "pending"
//   votesFor: number
//   votesAgainst: number
//   totalVotes: number
//   quorum: number
//   timeLeft: string
//   proposer: string
// }

// interface AppContextType {
//   // AI Models
//   aiModels: AIModel[]
//   featuredModels: AIModel[]
//   trendingModels: AIModel[]

//   // NFT Items
//   nftItems: NFTItem[]
//   myNFTs: NFTItem[]

//   // DAO
//   proposals: Proposal[]
//   userStake: number
//   votingPower: number

//   // User Data
//   userStats: {
//     totalEarnings: number
//     totalSales: number
//     activeListings: number
//     totalViews: number
//   }

//   // Functions
//   searchModels: (query: string, filters?: any) => AIModel[]
//   generateAIResponse: (prompt: string, modelId: string) => Promise<string>
//   mintNFT: (content: string, type: string) => Promise<void>
//   buyNFT: (nftId: string) => Promise<void>
//   rentModel: (modelId: string, duration: string) => Promise<void>
//   voteOnProposal: (proposalId: string, vote: "for" | "against") => Promise<void>
//   stakeTokens: (amount: number) => Promise<void>
// }

// const AppContext = createContext<AppContextType | undefined>(undefined)

// export function AppProvider({ children }: { children: ReactNode }) {
// //   const { toast } = useToast()

//   // Mock data - in production, this would come from APIs/blockchain
//   const [aiModels] = useState<AIModel[]>([
//     {
//       id: "gpt-4-turbo",
//       name: "GPT-4 Turbo",
//       description: "Advanced language model for text generation and analysis",
//       type: "text",
//       price: "2.5 ETH",
//       creator: "0x1234...5678",
//       image: "/placeholder.svg?height=200&width=300&text=GPT-4",
//       rating: 4.9,
//       downloads: 15420,
//       category: "Language Models",
//       isRental: false,
//     },
//     {
//       id: "dall-e-3",
//       name: "DALL-E 3 Pro",
//       description: "State-of-the-art image generation model",
//       type: "image",
//       price: "0.1 ETH/hour",
//       creator: "0xabcd...efgh",
//       image: "/placeholder.svg?height=200&width=300&text=DALL-E",
//       rating: 4.8,
//       downloads: 8930,
//       category: "Image Generation",
//       isRental: true,
//       rentalPrice: "0.1 ETH/hour",
//     },
//     {
//       id: "whisper-large",
//       name: "Whisper Large V3",
//       description: "High-accuracy speech recognition and transcription",
//       type: "audio",
//       price: "1.8 ETH",
//       creator: "0x9876...5432",
//       image: "/placeholder.svg?height=200&width=300&text=Whisper",
//       rating: 4.7,
//       downloads: 5670,
//       category: "Audio Processing",
//       isRental: false,
//     },
//     {
//       id: "codex-advanced",
//       name: "Codex Advanced",
//       description: "Advanced code generation and debugging assistant",
//       type: "code",
//       price: "0.05 ETH/use",
//       creator: "0xfedc...ba98",
//       image: "/placeholder.svg?height=200&width=300&text=Codex",
//       rating: 4.6,
//       downloads: 12340,
//       category: "Code Generation",
//       isRental: true,
//       rentalPrice: "0.05 ETH/use",
//     },
//     {
//       id: "stable-video",
//       name: "Stable Video Diffusion",
//       description: "Generate high-quality videos from text prompts",
//       type: "video",
//       price: "3.2 ETH",
//       creator: "0x5555...9999",
//       image: "/placeholder.svg?height=200&width=300&text=Video",
//       rating: 4.5,
//       downloads: 3210,
//       category: "Video Generation",
//       isRental: false,
//     },
//   ])

//   const [nftItems] = useState<NFTItem[]>([
//     {
//       id: "nft-1",
//       name: "Abstract AI Art #001",
//       description: "Unique digital art generated by AI",
//       price: "0.5 ETH",
//       creator: "0x1111...2222",
//       image: "/placeholder.svg?height=200&width=200&text=Art1",
//       type: "output",
//       category: "Digital Art",
//       likes: 234,
//       views: 1520,
//       isListed: true,
//     },
//     {
//       id: "nft-2",
//       name: "Perfect Prompt Collection",
//       description: "Curated prompts for image generation",
//       price: "0.1 ETH",
//       creator: "0x3333...4444",
//       image: "/placeholder.svg?height=200&width=200&text=Prompts",
//       type: "prompt",
//       category: "Prompt Engineering",
//       likes: 156,
//       views: 890,
//       isListed: true,
//     },
//   ])

//   const [proposals] = useState<Proposal[]>([
//     {
//       id: "prop-1",
//       title: "Reduce Marketplace Fees to 2%",
//       description: "Proposal to reduce the current 2.5% marketplace fee to 2% to attract more creators",
//       status: "active",
//       votesFor: 12500,
//       votesAgainst: 3200,
//       totalVotes: 15700,
//       quorum: 20000,
//       timeLeft: "2 days",
//       proposer: "0x1234...5678",
//     },
//     {
//       id: "prop-2",
//       title: "Add Support for Video AI Models",
//       description: "Integrate video generation AI models into the platform marketplace",
//       status: "passed",
//       votesFor: 18900,
//       votesAgainst: 2100,
//       totalVotes: 21000,
//       quorum: 20000,
//       timeLeft: "Ended",
//       proposer: "0xabcd...efgh",
//     },
//   ])

//   const [userStats] = useState({
//     totalEarnings: 21.5,
//     totalSales: 77,
//     activeListings: 12,
//     totalViews: 4200,
//   })

//   const [userStake] = useState(5000)
//   const [votingPower] = useState(5000)

//   const searchModels = (query: string, filters?: any): AIModel[] => {
//     let filtered = aiModels.filter(
//       (model) =>
//         model.name.toLowerCase().includes(query.toLowerCase()) ||
//         model.description.toLowerCase().includes(query.toLowerCase()) ||
//         model.category.toLowerCase().includes(query.toLowerCase()),
//     )

//     if (filters?.category && filters.category !== "All Categories") {
//       filtered = filtered.filter((model) => model.category === filters.category)
//     }

//     if (filters?.type && filters.type !== "all") {
//       filtered = filtered.filter((model) => model.type === filters.type)
//     }

//     if (filters?.priceRange) {
//       // Implement price filtering logic
//     }

//     return filtered
//   }

//   const generateAIResponse = async (prompt: string, modelId: string): Promise<string> => {
//     const model = aiModels.find((m) => m.id === modelId)
//     if (!model) throw new Error("Model not found")

//     // Simulate API call delay
//     await new Promise((resolve) => setTimeout(resolve, 2000))

//     // Generate mock response based on model type
//     switch (model.type) {
//       case "text":
//         return `AI Response from ${model.name}:\n\nThis is a simulated response to your prompt: "${prompt}"\n\nIn a production environment, this would connect to the actual AI model via OpenxAI Xnodes or LocalAI/Ollama for decentralized, uncensored AI inference.`
//       case "image":
//         return `Image generated successfully using ${model.name}. In production, this would return the actual generated image URL.`
//       case "code":
//         return `// Code generated by ${model.name}\n// Prompt: ${prompt}\n\nfunction exampleFunction() {\n  // This is simulated code generation\n  console.log("Hello from AI-generated code!");\n  return "Generated based on: ${prompt}";\n}`
//       case "audio":
//         return `Audio processed successfully using ${model.name}. Generated audio file would be available for download.`
//       default:
//         return `Response generated by ${model.name} for prompt: "${prompt}"`
//     }
//   }

//   const mintNFT = async (content: string, type: string): Promise<void> => {
// //     toast({
// //       title: "Minting NFT...",
// //       description: "Your content is being minted as an NFT",
// //     })

//     // Simulate blockchain transaction
//     await new Promise((resolve) => setTimeout(resolve, 3000))

// //     toast({
// //       title: "NFT Minted Successfully!",
// //       description: "Your NFT has been created and added to your collection",
// //     })
//   }

//   const buyNFT = async (nftId: string): Promise<void> => {
//     const nft = nftItems.find((item) => item.id === nftId)
//     if (!nft) throw new Error("NFT not found")

// //     toast({
// //       title: "Processing Purchase...",
// //       description: `Buying ${nft.name} for ${nft.price}`,
// //     })

//     await new Promise((resolve) => setTimeout(resolve, 2000))

// //     toast({
// //       title: "Purchase Successful!",
// //       description: `You now own ${nft.name}`,
// //     })
//   }

//   const rentModel = async (modelId: string, duration: string): Promise<void> => {
//     const model = aiModels.find((m) => m.id === modelId)
//     if (!model) throw new Error("Model not found")

// //     toast({
// //       title: "Processing Rental...",
// //       description: `Renting ${model.name} for ${duration}`,
// //     })

//     await new Promise((resolve) => setTimeout(resolve, 2000))

// //     toast({
// //       title: "Rental Successful!",
// //       description: `You can now use ${model.name} for ${duration}`,
// //     })
//   }

//   const voteOnProposal = async (proposalId: string, vote: "for" | "against"): Promise<void> => {
 

//     await new Promise((resolve) => setTimeout(resolve, 1500))

// //     toast({
// //       title: "Vote Submitted!",
// //       description: "Your vote has been recorded on the blockchain",
// //     })
//   }

//   const stakeTokens = async (amount: number): Promise<void> => {
// //     toast({
// //       title: "Staking Tokens...",
// //       description: `Staking ${amount} ALX tokens`,
// //     })

//     await new Promise((resolve) => setTimeout(resolve, 2000))

// //     toast({
// //       title: "Staking Successful!",
// //       description: `${amount} ALX tokens have been staked`,
// //     })
//   }

//   const value: AppContextType = {
//     aiModels,
//     featuredModels: aiModels.slice(0, 3),
//     trendingModels: aiModels.slice(1, 4),
//     nftItems,
//     myNFTs: nftItems.slice(0, 2),
//     proposals,
//     userStake,
//     votingPower,
//     userStats,
//     searchModels,
//     generateAIResponse,
//     mintNFT,
//     buyNFT,
//     rentModel,
//     voteOnProposal,
//     stakeTokens,
//   }

//   return <AppContext.Provider value={value}>{children}</AppContext.Provider>
// }

// export function useApp() {
//   const context = useContext(AppContext)
//   if (context === undefined) {
//     throw new Error("useApp must be used within an AppProvider")
//   }
//   return context
// }



//  veriosn 2 
"use client"

import { createContext, useContext, useState, type ReactNode } from "react"
// import { useToast } from "@/hooks/use-toast"

interface AIModel {
  id: string
  name: string
  description: string
  type: "text" | "image" | "audio" | "video" | "code"
  price: string
  creator: string
  image: string
  rating: number
  downloads: number
  category: string
  isRental: boolean
  rentalPrice?: string
}

interface NFTItem {
  id: string
  name: string
  description: string
  price: string
  creator: string
  image: string
  type: "model" | "prompt" | "output"
  category: string
  likes: number
  views: number
  isListed: boolean
}

interface Proposal {
  id: string
  title: string
  description: string
  status: "active" | "passed" | "failed" | "pending"
  votesFor: number
  votesAgainst: number
  totalVotes: number
  quorum: number
  timeLeft: string
  proposer: string
}

interface AppContextType {
  // AI Models
  aiModels: AIModel[]
  featuredModels: AIModel[]
  trendingModels: AIModel[]

  // NFT Items
  nftItems: NFTItem[]
  myNFTs: NFTItem[]

  // DAO
  proposals: Proposal[]
  userStake: number
  votingPower: number

  // User Data
  userStats: {
    totalEarnings: number
    totalSales: number
    activeListings: number
    totalViews: number
  }

  // Functions
  searchModels: (query: string, filters?: any) => AIModel[]
  generateAIResponse: (prompt: string, modelId: string) => Promise<string>
  mintNFT: (content: string, type: string) => Promise<void>
  buyNFT: (nftId: string) => Promise<void>
  rentModel: (modelId: string, duration: string) => Promise<void>
  voteOnProposal: (proposalId: string, vote: "for" | "against") => Promise<void>
  stakeTokens: (amount: number) => Promise<void>
}

const AppContext = createContext<AppContextType | undefined>(undefined)

export function AppProvider({ children }: { children: ReactNode }) {
//   const { toast } = useToast()

  // Mock data - in production, this would come from APIs/blockchain
  const [aiModels] = useState<AIModel[]>([
    {
      id: "gpt-4-turbo",
      name: "GPT-4 Turbo",
      description: "Advanced language model for text generation and analysis",
      type: "text",
      price: "2.5 ETH",
      creator: "0x1234...5678",
      image: "/placeholder.svg?height=200&width=300&text=GPT-4",
      rating: 4.9,
      downloads: 15420,
      category: "Language Models",
      isRental: false,
    },
    {
      id: "dall-e-3",
      name: "DALL-E 3 Pro",
      description: "State-of-the-art image generation model",
      type: "image",
      price: "0.1 ETH/hour",
      creator: "0xabcd...efgh",
      image: "/placeholder.svg?height=200&width=300&text=DALL-E",
      rating: 4.8,
      downloads: 8930,
      category: "Image Generation",
      isRental: true,
      rentalPrice: "0.1 ETH/hour",
    },
    {
      id: "whisper-large",
      name: "Whisper Large V3",
      description: "High-accuracy speech recognition and transcription",
      type: "audio",
      price: "1.8 ETH",
      creator: "0x9876...5432",
      image: "/placeholder.svg?height=200&width=300&text=Whisper",
      rating: 4.7,
      downloads: 5670,
      category: "Audio Processing",
      isRental: false,
    },
    {
      id: "codex-advanced",
      name: "Codex Advanced",
      description: "Advanced code generation and debugging assistant",
      type: "code",
      price: "0.05 ETH/use",
      creator: "0xfedc...ba98",
      image: "/placeholder.svg?height=200&width=300&text=Codex",
      rating: 4.6,
      downloads: 12340,
      category: "Code Generation",
      isRental: true,
      rentalPrice: "0.05 ETH/use",
    },
    {
      id: "stable-video",
      name: "Stable Video Diffusion",
      description: "Generate high-quality videos from text prompts",
      type: "video",
      price: "3.2 ETH",
      creator: "0x5555...9999",
      image: "/placeholder.svg?height=200&width=300&text=Video",
      rating: 4.5,
      downloads: 3210,
      category: "Video Generation",
      isRental: false,
    },
  ])

  const [nftItems] = useState<NFTItem[]>([
    {
      id: "nft-1",
      name: "Abstract AI Art #001",
      description: "Unique digital art generated by AI",
      price: "0.5 ETH",
      creator: "0x1111...2222",
      image: "/placeholder.svg?height=200&width=200&text=Art1",
      type: "output",
      category: "Digital Art",
      likes: 234,
      views: 1520,
      isListed: true,
    },
    {
      id: "nft-2",
      name: "Perfect Prompt Collection",
      description: "Curated prompts for image generation",
      price: "0.1 ETH",
      creator: "0x3333...4444",
      image: "/placeholder.svg?height=200&width=200&text=Prompts",
      type: "prompt",
      category: "Prompt Engineering",
      likes: 156,
      views: 890,
      isListed: true,
    },
  ])

  const [proposals] = useState<Proposal[]>([
    {
      id: "prop-1",
      title: "Reduce Marketplace Fees to 2%",
      description: "Proposal to reduce the current 2.5% marketplace fee to 2% to attract more creators",
      status: "active",
      votesFor: 12500,
      votesAgainst: 3200,
      totalVotes: 15700,
      quorum: 20000,
      timeLeft: "2 days",
      proposer: "0x1234...5678",
    },
    {
      id: "prop-2",
      title: "Add Support for Video AI Models",
      description: "Integrate video generation AI models into the platform marketplace",
      status: "passed",
      votesFor: 18900,
      votesAgainst: 2100,
      totalVotes: 21000,
      quorum: 20000,
      timeLeft: "Ended",
      proposer: "0xabcd...efgh",
    },
  ])

  const [userStats] = useState({
    totalEarnings: 21.5,
    totalSales: 77,
    activeListings: 12,
    totalViews: 4200,
  })

  const [userStake] = useState(5000)
  const [votingPower] = useState(5000)

  const searchModels = (query: string, filters?: any): AIModel[] => {
    let filtered = aiModels.filter(
      (model) =>
        model.name.toLowerCase().includes(query.toLowerCase()) ||
        model.description.toLowerCase().includes(query.toLowerCase()) ||
        model.category.toLowerCase().includes(query.toLowerCase()),
    )

    if (filters?.category && filters.category !== "All Categories") {
      filtered = filtered.filter((model) => model.category === filters.category)
    }

    if (filters?.type && filters.type !== "all") {
      filtered = filtered.filter((model) => model.type === filters.type)
    }

    if (filters?.priceRange) {
      // Implement price filtering logic
    }

    return filtered
  }

  const generateAIResponse = async (prompt: string, modelId: string): Promise<string> => {
    const model = aiModels.find((m) => m.id === modelId)
    if (!model) throw new Error("Model not found")

    // Simulate API call delay
    await new Promise((resolve) => setTimeout(resolve, 2000))

    // Generate mock response based on model type
    switch (model.type) {
      case "text":
        return `AI Response from ${model.name}:\n\nThis is a simulated response to your prompt: "${prompt}"\n\nIn a production environment, this would connect to the actual AI model via OpenxAI Xnodes or LocalAI/Ollama for decentralized, uncensored AI inference.`
      case "image":
        return `Image generated successfully using ${model.name}. In production, this would return the actual generated image URL.`
      case "code":
        return `// Code generated by ${model.name}\n// Prompt: ${prompt}\n\nfunction exampleFunction() {\n  // This is simulated code generation\n  console.log("Hello from AI-generated code!");\n  return "Generated based on: ${prompt}";\n}`
      case "audio":
        return `Audio processed successfully using ${model.name}. Generated audio file would be available for download.`
      default:
        return `Response generated by ${model.name} for prompt: "${prompt}"`
    }
  }

  const mintNFT = async (content: string, type: string): Promise<void> => {
//     toast({
//       title: "Minting NFT...",
//       description: "Your content is being minted as an NFT",
//     })

    // Simulate blockchain transaction
    await new Promise((resolve) => setTimeout(resolve, 3000))

//     toast({
//       title: "NFT Minted Successfully!",
//       description: "Your NFT has been created and added to your collection",
//     })
  }

  const buyNFT = async (nftId: string): Promise<void> => {
    const nft = nftItems.find((item) => item.id === nftId)
    if (!nft) throw new Error("NFT not found")

//     toast({
//       title: "Processing Purchase...",
//       description: `Buying ${nft.name} for ${nft.price}`,
//     })

    await new Promise((resolve) => setTimeout(resolve, 2000))

//     toast({
//       title: "Purchase Successful!",
//       description: `You now own ${nft.name}`,
//     })
  }

  const rentModel = async (modelId: string, duration: string): Promise<void> => {
    const model = aiModels.find((m) => m.id === modelId)
    if (!model) throw new Error("Model not found")

//     toast({
//       title: "Processing Rental...",
//       description: `Renting ${model.name} for ${duration}`,
//     })

    await new Promise((resolve) => setTimeout(resolve, 2000))

//     toast({
//       title: "Rental Successful!",
//       description: `You can now use ${model.name} for ${duration}`,
//     })
  }

  const voteOnProposal = async (proposalId: string, vote: "for" | "against"): Promise<void> => {
 

    await new Promise((resolve) => setTimeout(resolve, 1500))

//     toast({
//       title: "Vote Submitted!",
//       description: "Your vote has been recorded on the blockchain",
//     })
  }

  const stakeTokens = async (amount: number): Promise<void> => {
//     toast({
//       title: "Staking Tokens...",
//       description: `Staking ${amount} ALX tokens`,
//     })

    await new Promise((resolve) => setTimeout(resolve, 2000))

//     toast({
//       title: "Staking Successful!",
//       description: `${amount} ALX tokens have been staked`,
//     })
  }

  const value: AppContextType = {
    aiModels,
    featuredModels: aiModels.slice(0, 3),
    trendingModels: aiModels.slice(1, 4),
    nftItems,
    myNFTs: nftItems.slice(0, 2),
    proposals,
    userStake,
    votingPower,
    userStats,
    searchModels,
    generateAIResponse,
    mintNFT,
    buyNFT,
    rentModel,
    voteOnProposal,
    stakeTokens,
  }

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>
}

export function useApp() {
  const context = useContext(AppContext)
  if (context === undefined) {
    throw new Error("useApp must be used within an AppProvider")
  }
  return context
}
